project:
  type: website
  output-dir: docs #사이트 상태인 걸 docs 파일로 저장
  #index에서 preview 한 후 sites 파일 폴더 제거
  
website:
  title: "hyonjae-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



